Feature/en 14 make two buttons for answers
A-Romany/englishbot pull request #4
Opened 2020-08-30 17:39 UTC by A-Romany

2020-08-30 18:10 UTC, AgienkoSergiy requested changes

2020-08-30 18:10 UTC, AgienkoSergiy commented on src/main/java/org/agbrothers/englishbot/constant/MessageLabel.java
> +    public static final String PROBEL = " ";
PROBEL? :) English please

2020-08-30 18:10 UTC, AgienkoSergiy commented on src/main/java/org/agbrothers/englishbot/constant/MessageLabel.java
> +    public static final String FROM = "із";
I suppose there are no so many usages of this string in code, hence it does'nt need to be constant

2020-08-30 18:10 UTC, AgienkoSergiy commented on src/main/resources/application.yml
> +  bot.server.url: https://c8340a23baed.ngrok.io
exclude this file from commit please

2020-08-30 18:12 UTC, A-Romany commented on src/main/resources/application.yml
> +  bot.server.url: https://c8340a23baed.ngrok.io
ok

2020-08-31 17:44 UTC, AgienkoSergiy approved these changes

2020-08-31 17:49 UTC, merged